# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
