# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Invitation', '0002_auto_20171108_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishe',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
